services:
  - type: web
    name: backend-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi --chdir proyecto-fullstack/backend
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
